### ISSUE TITLE
Unknown failure: :nxdomain when running application.

### ISSUE THREAD

**Issue by RafaJimenezR98** [Bluetab/td-dd#1]
Hello, I try to run the application and I am getting all the time the same error:

`2020-02-07T10:45:46.290Z [error] pid=<0.1870.0> module=DBConnection.Connection Bolt.Sips.Protocol (#PID<0.1870.0>) failed to connect: ** (Bolt.Sips.Internals.Error) connect: Unknown failure: :nxdomain`

The application seems that is running but in the console I can only see that error,

thanks in advance.

**Comment by tcrossland** [comment]
The Data Dictionary service is looking for a Neo4J server. By default it's looking for a hostname called "neo". If you're running the service locally, you can disable Neo4J integration by adding the following configuration to your `config/dev.exs` file:

```elixir
config: :bolt_sips, Bolt,
  hostname: ""
```

Alternatively, you could set up a Neo4J server and specify the configuration in `config/dev.exs`:

```elixir
config :bolt_sips, Bolt,
  hostname: "my_neo4j_host",
  basic_auth: [username: "neo4j", password: "my_neo4j_password"],
```

**Comment by RafaJimenezR98** [comment]
Thanks for your help, It is working.
